### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by banool** [samirelanduk/tiktok-save#15]
I see a previous instance of this issue https://github.com/samirelanduk/tiktok-save/issues/11, but it was closed without being resolved, so I'm opening this to track.

Repro is simple, just follow the README and you'll get this error:
```
$ python save.py bookmarked user_data.json bookmarked/
  0%|                                                                                           | 0/428 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/dport/github/tiktok-save/save.py", line 49, in <module>
    tiktok_dict = api.get_tiktok_by_id(tiktok_id, custom_did=did)
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 1077, in get_tiktok_by_id
    return self.get_data(url=api_url, **kwargs)
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 229, in get_data
    verify_fp, did, signature = self.browser.sign_url(**kwargs)
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/TikTokApi/browser.py", line 188, in sign_url
    evaluatedPage = page.evaluate(
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8710, in evaluate
    self._sync(
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/_impl/_page.py", line 391, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 272, in evaluate
    await self._channel.send(
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "/Users/dport/github/tiktok-save/myvenv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.Error: TypeError: undefined is not an object (evaluating 'S[A][m(a[oprand[1]],oprand[1])]')
```

**Comment by evelynmatson** [comment]
+1. Did you ever solve this?
